### ISSUE TITLE
Is this repository still used or outdated?

### ISSUE THREAD

**Issue by junaruga** [fedora-modularity/dependency-report#12]
Because ruby.yaml is referring this repository.

https://src.fedoraproject.org/modules/ruby/blob/master/f/ruby.yaml#_1-2

> \# Keep a generated ruby.yaml file URL here to follow latest configuration.
> \# https://github.com/fedora-modularity/dependency-report/blob/master/modules/ruby/ruby.yaml

**Comment by contyk** [comment]
Yeah, this is pretty dead. We don't generate modules for anyone anymore.

**Comment by junaruga** [comment]
@contyk okay, maybe this repository can be archived to show the dead status clearly to users?

**Comment by contyk** [comment]
Yes, I believe the plan is to close these. @asamalik ?

**Comment by asamalik** [comment]
It is inactive, yes. I have already deleted tens of repositories under modularity-modules, I will also look at the ones under this github organization.
